import { ReactElement } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@/components/Button'
import { attributes, react as HomeContent } from '../content/home.md'
import styles from './index.module.scss'

export default function Home(): ReactElement {
  const { title, cats } = attributes

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>

        <Button label="A starter by Codegram" primary />

        <HomeContent />

        <ul>
          {cats.map((cat) => (
            <li key={cat.name}>
              <h2>{cat.name}</h2>
              <p>{cat.description}</p>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
