import { ReactElement } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@/components'

import { GetStaticPropsResult } from 'next'
import { RichText, RichTextBlock } from 'prismic-reactjs'
import { IndexPageDocument, IndexPageQuery } from '@/graphql/types'
import { client } from '@/graphql/client'

import styles from './index.module.scss'

export type HomeProps = {
  title: RichTextBlock[]
}

export async function getStaticProps(): Promise<
  GetStaticPropsResult<HomeProps>
> {
  const { data } = await client.query<IndexPageQuery>({
    query: IndexPageDocument,
  })

  return {
    props: {
      title: data.allHomepages.edges[0].node.title,
    },
  }
}

export default function Home({ title }: HomeProps): ReactElement {
  return (
    <div className={styles.container}>
      <Head>
        <title>{RichText.asText(title)}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>

        <Button label="A starter by Codegram" primary />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
