# Note: In order for this action to run, you need to install this app
# on your repository first: https://github.com/apps/dependabot-merge-action

name: Dependabot automerge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
